version: "3"
services:

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd!
      - MYSQL_DATABASE=gymsystem
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=P@ssw0rd!
